services:
  - type: web
    name: budgetiq-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FRONTEND_URL
        value: https://ai-budgetiq.vercel.app
      - key: GEMINI_API_KEY
        sync: false
